// This file is automatically generated. Do not edit it directly.
//
// Güvenli Supabase client fabrikası:
// - import.meta.env (Vite) ve process.env (CI / server) için uyumlu.
// - ENV eksikse uygulamanın tamamen çökmesini engellemek için açık hata veren bir "stub" döner.
// - Tarayıcı ortamında localStorage mevcutsa auth.storage konfigürasyonu eklenir.

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/** import.meta.env veya process.env içinden bir değişken okur */
function getEnv(name: string): string | undefined {
  try {
    const v = (import.meta as any)?.env?.[name];
    if (typeof v === "string" && v.length > 0) return v;
  } catch {
    // import.meta yoksa yoksay
  }
  const p = (process as any)?.env?.[name];
  if (typeof p === "string" && p.length > 0) return p;
  return undefined;
}

const SUPABASE_URL = getEnv("VITE_SUPABASE_URL") ?? "";
const SUPABASE_PUBLISHABLE_KEY =
  getEnv("VITE_SUPABASE_PUBLISHABLE_KEY") ?? getEnv("VITE_SUPABASE_ANON_KEY") ?? "";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    "[supabase/client] VITE_SUPABASE_URL veya VITE_SUPABASE_PUBLISHABLE_KEY tanımlı değil. " +
      "Lütfen proje kökünde .env dosyasına bu değişkenleri ekleyip dev server'ı yeniden başlatın. " +
      "(Not: anahtarları repoya commit etmeyin.)"
  );

  // Basit stub: uygulamanın tamamının çökmesini engeller. Gerçek DB çağrısı yapıldığında açık hata atılır.
  const stub = {
    auth: {
      getUser: async () => ({ data: { user: null }, error: null }),
      signInWithPassword: async () => ({ data: null, error: new Error("Supabase yapılandırılmadı") }),
      signOut: async () => ({ error: new Error("Supabase yapılandırılmadı") }),
    },
    from: (table: string) => ({
      select: async (..._args: any[]) => {
        throw new Error(`Supabase yapılandırılmadı. Denenen tablo: ${table}`);
      },
      insert: async (..._args: any[]) => {
        throw new Error(`Supabase yapılandırılmadı. Denenen tablo: ${table}`);
      },
      update: async (..._args: any[]) => {
        throw new Error(`Supabase yapılandırılmadı. Denenen tablo: ${table}`);
      },
      delete: async (..._args: any[]) => {
        throw new Error(`Supabase yapılandırılmadı. Denenen tablo: ${table}`);
      },
    }),
  } as unknown;

  export const supabase: any = stub;
} else {
  // Tarayıcı ortamındaysak localStorage'ı auth.storage olarak verelim; SSR ortamında bunu eklemeyelim.
  const authOptions: Record<string, any> = {
    persistSession: true,
    autoRefreshToken: true,
  };
  if (typeof window !== "undefined" && typeof window.localStorage !== "undefined") {
    authOptions.storage = window.localStorage;
  }

  export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: authOptions,
  });
}
